### ISSUE TITLE
Add better handling of invalid variable formats

### ISSUE THREAD

**Issue by ctaymor** [ljfranklin/terraform-resource#16]
We got the following panic when there were multiline values without the appropriate yaml syntax for multiline values in the vars section.

```
▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ Terraform Destroy ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼
▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Destroy ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x523fed]

goroutine 1 [running]:
panic(0x7ccc20, 0xc420012080)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
terraform-resource/terraform.formatVar(0x0, 0x0, 0xc4204d2f50, 0x2)
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/terraform/client.go:151 +0x7d
terraform-resource/terraform.Client.varFlags(0xc42016ce00, 0x10, 0xc42043a690, 0xc4201900c0, 0x2e, 0x0, 0xc420072d80, 0x36, 0xc420184980, 0x12, ...)
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/terraform/client.go:144 +0x10a
terraform-resource/terraform.Client.Destroy(0xc42016ce00, 0x10, 0xc42043a690, 0xc4201900c0, 0x2e, 0x0, 0xc420072d80, 0x36, 0xc420184980, 0x12, ...)
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/terraform/client.go:99 +0x614
terraform-resource/terraform.Action.attemptDestroy(0xc42016ce00, 0x10, 0xc42043a690, 0xc4201900c0, 0x2e, 0x0, 0xc420072d80, 0x36, 0xc420184980, 0x12, ...)
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/terraform/action.go:120 +0xdf
terraform-resource/terraform.Action.Destroy(0xc42016ce00, 0x10, 0xc42043a690, 0xc4201900c0, 0x2e, 0x0, 0xc420072d80, 0x36, 0xc420184980, 0x12, ...)
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/terraform/action.go:99 +0xbc
terraform-resource/out.Runner.Run(0x7fff00022ecf, 0xe, 0xa16c80, 0xa5d298, 0xa16840, 0xc420094010, 0xc42016ca18, 0x2, 0xc420184080, 0x1c, ...)
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/out/out.go:89 +0xdd8
main.main()
	/tmp/build/9d0884a1/resource-src/src/terraform-resource/cmd/out/main.go:32 +0x273
```

**Comment by ljfranklin** [comment]
Thanks for the heads up @ctaymor, fixed here: https://github.com/ljfranklin/terraform-resource/commit/688c9e9783641bd6413f694619a6e149ca066a84
